# Generated by Django 5.1.6 on 2025-02-14 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('data', models.DateTimeField(verbose_name='Data')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Hierarquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Hierarquia',
                'verbose_name_plural': 'Hierarquias',
            },
        ),
        migrations.CreateModel(
            name='Terreiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('documento', models.FileField(upload_to='documentos/terreiro/', verbose_name='Documento')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('data_fundacao', models.DateField(verbose_name='Data de Fundação')),
                ('rua', models.CharField(max_length=255, verbose_name='Rua')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Terreiro',
                'verbose_name_plural': 'Terreiros',
            },
        ),
        migrations.CreateModel(
            name='Mediun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('documento', models.CharField(blank=True, max_length=14, null=True, verbose_name='Documento (CPF)')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cargos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.cargo', verbose_name='Cargo')),
                ('hierarquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.hierarquia', verbose_name='Hierarquia')),
            ],
            options={
                'verbose_name': 'Médio',
                'verbose_name_plural': 'Médiuns',
            },
        ),
        migrations.CreateModel(
            name='CaminhadaEspiritual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('data_batismo', models.DateField(blank=True, null=True, verbose_name='Data de Batismo')),
                ('data_obori', models.DateField(blank=True, null=True, verbose_name='Data de Obori')),
                ('data_pai_mae_pequeno', models.DateField(blank=True, null=True, verbose_name='Data Pai/Mãe Pequeno')),
                ('data_baba_ya', models.DateField(blank=True, null=True, verbose_name='Data Babá Ya')),
                ('data_reforco7', models.DateField(blank=True, null=True, verbose_name='Data Reforço 7 Dias')),
                ('data_reforco14', models.DateField(blank=True, null=True, verbose_name='Data Reforço 14 Dias')),
                ('data_reforco21', models.DateField(blank=True, null=True, verbose_name='Data Reforço 21 Dias')),
                ('data_desligamento', models.DateField(blank=True, null=True, verbose_name='Data de Desligamento')),
                ('mediun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caminhada_espiritual', to='gestao.mediun')),
            ],
            options={
                'verbose_name': 'Caminhada Espiritual',
                'verbose_name_plural': 'Caminhadas Espirituais',
            },
        ),
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('paga', models.BooleanField(default=False, verbose_name='Paga')),
                ('mediun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.mediun', verbose_name='Médio')),
            ],
            options={
                'verbose_name': 'Mensalidade',
                'verbose_name_plural': 'Mensalidades',
            },
        ),
        migrations.AddField(
            model_name='hierarquia',
            name='terreiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hierarquias', to='gestao.terreiro', verbose_name='Terreiro'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='terreiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='gestao.terreiro', verbose_name='Terreiro'),
        ),
    ]
