# Generated by Django 5.1.6 on 2025-02-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terreiro',
            name='documento',
            field=models.CharField(max_length=15, verbose_name='Documento (CNPJ)'),
        ),
    ]
