# Generated by Django 5.1.6 on 2025-02-14 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_alter_terreiro_documento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediun',
            options={'verbose_name': 'Mediun', 'verbose_name_plural': 'Médiuns'},
        ),
        migrations.AlterField(
            model_name='caminhadaespiritual',
            name='data_reforco14',
            field=models.DateField(blank=True, null=True, verbose_name='Data Reforço 14 Anos'),
        ),
        migrations.AlterField(
            model_name='caminhadaespiritual',
            name='data_reforco21',
            field=models.DateField(blank=True, null=True, verbose_name='Data Reforço 21 Anos'),
        ),
        migrations.AlterField(
            model_name='caminhadaespiritual',
            name='data_reforco7',
            field=models.DateField(blank=True, null=True, verbose_name='Data Reforço 7 Anos'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='mediun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.mediun', verbose_name='Mediun'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor R$:'),
        ),
        migrations.CreateModel(
            name='RegistroEspiritual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_santo', models.CharField(max_length=100, verbose_name='Primeiro Santo')),
                ('segundo_santo', models.CharField(max_length=100, verbose_name='Segundo Santo')),
                ('exu', models.CharField(max_length=100, verbose_name='Exu')),
                ('pomba_gira', models.CharField(max_length=100, verbose_name='Pomba Gira')),
                ('preto_velho', models.CharField(max_length=100, verbose_name='Preto Velho')),
                ('caboclo', models.CharField(max_length=100, verbose_name='Caboclo')),
                ('ibeijada', models.CharField(max_length=100, verbose_name='Ibeijada')),
                ('responsavel_coroa', models.CharField(max_length=100, verbose_name='Responsável pela Coroa')),
                ('padrinho_espiritual', models.CharField(max_length=100, verbose_name='Padrinho Espiritual')),
                ('madrinha_espiritual', models.CharField(max_length=100, verbose_name='Madrinha Espiritual')),
                ('padrinho_batismo', models.CharField(max_length=100, verbose_name='Padrinho Batismo')),
                ('madrinha_batismo', models.CharField(max_length=100, verbose_name='Madrinha Batismo')),
                ('mediun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_espiritual', to='gestao.mediun')),
            ],
            options={
                'verbose_name': 'Registro Espiritual',
                'verbose_name_plural': 'Registros Espirituais',
            },
        ),
    ]
