# Generated by Django 5.1.6 on 2025-02-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_alter_mediun_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caminhadaespiritual',
            options={'verbose_name': 'Caminhada Espiritual'},
        ),
        migrations.AlterField(
            model_name='registroespiritual',
            name='caboclo',
            field=models.CharField(max_length=100, null=True, verbose_name='Caboclo'),
        ),
        migrations.AlterField(
            model_name='registroespiritual',
            name='exu',
            field=models.CharField(max_length=100, null=True, verbose_name='Exu'),
        ),
        migrations.AlterField(
            model_name='registroespiritual',
            name='ibeijada',
            field=models.CharField(max_length=100, null=True, verbose_name='Ibeijada'),
        ),
        migrations.AlterField(
            model_name='registroespiritual',
            name='madrinha_batismo',
            field=models.CharField(max_length=100, null=True, verbose_name='Madrinha Batismo'),
        ),
        migrations.AlterField(
            model_name='registroespiritual',
            name='madrinha_espiritual',
            field=models.CharField(max_length=100, null=True, verbose_name='Madrinha Espiritual'),
        ),
        migrations.AlterField(
            model_name='registroespiritual',
            name='padrinho_batismo',
            field=models.CharField(max_length=100, null=True, verbose_name='Padrinho Batismo'),
        ),
        migrations.AlterField(
            model_name='registroespiritual',
            name='padrinho_espiritual',
            field=models.CharField(max_length=100, null=True, verbose_name='Padrinho Espiritual'),
        ),
        migrations.AlterField(
            model_name='registroespiritual',
            name='pomba_gira',
            field=models.CharField(max_length=100, null=True, verbose_name='Pomba Gira'),
        ),
        migrations.AlterField(
            model_name='registroespiritual',
            name='preto_velho',
            field=models.CharField(max_length=100, null=True, verbose_name='Preto Velho'),
        ),
        migrations.AlterField(
            model_name='registroespiritual',
            name='primeiro_santo',
            field=models.CharField(max_length=100, null=True, verbose_name='Primeiro Santo'),
        ),
        migrations.AlterField(
            model_name='registroespiritual',
            name='responsavel_coroa',
            field=models.CharField(max_length=100, null=True, verbose_name='Responsável pela Coroa'),
        ),
        migrations.AlterField(
            model_name='registroespiritual',
            name='segundo_santo',
            field=models.CharField(max_length=100, null=True, verbose_name='Segundo Santo'),
        ),
    ]
