# Generated by Django 5.1.6 on 2025-02-16 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_alter_registroespiritual_caboclo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroespiritual',
            name='responsavel_coroa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável anjo de guarda'),
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200, verbose_name='Item')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('mes', models.DateField(verbose_name='Data')),
                ('mediun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.mediun', verbose_name='Mediun')),
            ],
        ),
    ]
