# Generated by Django 5.1.6 on 2025-02-16 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_alter_registroespiritual_responsavel_coroa_compras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistribuicaoItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.mediun')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.item')),
            ],
        ),
        migrations.CreateModel(
            name='ListaCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('itens', models.ManyToManyField(through='gestao.DistribuicaoItens', to='gestao.item')),
            ],
        ),
        migrations.AddField(
            model_name='distribuicaoitens',
            name='lista_compras',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.listacompras'),
        ),
        migrations.DeleteModel(
            name='Compras',
        ),
    ]
