# Generated by Django 5.1.6 on 2025-02-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_item_distribuicaoitens_listacompras_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribuicaoitens',
            name='lista_compras',
        ),
        migrations.AddField(
            model_name='distribuicaoitens',
            name='data_distribuicao',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.DeleteModel(
            name='ListaCompras',
        ),
    ]
