# Generated by Django 5.1.6 on 2025-02-18 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_remove_distribuicaoitens_lista_compras_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distribuicaoitens',
            options={'verbose_name': 'Distribuição de Iten'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterModelOptions(
            name='terreiro',
            options={'verbose_name': 'Terreiro'},
        ),
    ]
